### ISSUE TITLE
Allow passing custom cert

### ISSUE THREAD

**Issue by will-in-wi** [code-mancers/invoker#197]
Invoker uses the included self-signed certificate from EventMachine. Could a feature be added to allow us to provide a custom certificate chain and key?

**Comment by kgrz** [comment]
Oh! that sounds like a cool feature! Do you have any idea/pointers how the API would look like in the config?

**Comment by will-in-wi** [comment]
Probably reflect the EventMachine config: http://www.rubydoc.info/github/eventmachine/eventmachine/EventMachine/Connection:start_tls

```ruby
:private_key_file => '/tmp/server.key', :cert_chain_file => '/tmp/server.crt', :verify_peer => false
```

If you don't care about the abstraction being leaky, you could potentially allow the user to arbitrarily modify the hash passed to `EventMachine::Connection#start_tls`. That would give maximum flexibility.

**Comment by gnufied** [comment]
There are two ways  we could do this:

1. Add support for specifying the certificates via CLI argument to `invoker start` command. Something like - `invoker start --cert="/foo.crt" --private_key="/foo.key"` . This would obviously mean that all services managed by Invoker will use same certificate.  Obviously, current implementation forces that default too.

2. We *can* potentially make it configurable for each service and make it part of `invoker.ini` file.  Obviously such a configuration will not be supported by Procfiles. 

@will-in-wi what is your use case of using custom certs btw? Do you have proper certificates that you want to use with Invoker rather than default Eventmachine supplied ones?

**Comment by will-in-wi** [comment]
My use case is to have a locally trusted custom CA, from which I would issue a `*.dev` TLD wildcard cert. I already have this CA for other dev work, and it'd be helpful to use it for this.

Also, there is a potential security vulnerability to using a cert with a publicly available private key. If that cert were marked as trusted by the user, they've now opened themselves to MITM attacks from attackers using this key.

**Comment by will-in-wi** [comment]
With all of that in mind, I'd probably start with option 1. If you want to do option 2 as well, that might be nice, though I wouldn't personally use it.

**Comment by gnufied** [comment]
Alright I will try and get a patch that makes it configurable via CLI knocked up. But if someone beats me to the punch and opens a PR, that would be awesome too. @kgrz what you think?

**Comment by kgrz** [comment]
I'm inclined more toward option 2. May be under a `[default]` section.

**Comment by gnufied** [comment]
hmm, for feature itself I would say lets follow YAGNI and just implement global flags for user specified certs and private key. If there is a demand for per app ssl certs - we can revisit this topic. Implementing global certs is hardly 10 line change.

**Comment by will-in-wi** [comment]
@gnufied Do you have any pointers as to where you would put the configuration? I can try to assemble a PR if I knew where to start.

Thanks!

**Comment by gnufied** [comment]
@will-in-wi rather than putting in configuration, i think we can make this CLI params to invoker start. `invoker start --cert="/foo.crt" --private_key="/foo.key"`
