### ISSUE TITLE
Invoker should allow pry or debugger to work with managed processes

### ISSUE THREAD

**Issue by gnufied** [code-mancers/invoker#2]

**Comment by madsheep** [comment]
@emilsoman To be honest using pry-remote feels much more unstable and far less comfortable than pure pry workflow. I've team members refusing to use invoker (and any other process mng tool like foreman for that matter) because of lack of ability to use pry 'normally' 

@gnufied Any chance this could become native feature for invoker? Maybe with some sort of plugin for pry?

**Comment by madsheep** [comment]
@gnufied any updates?

**Comment by etherbob** [comment]
pry-remote doesn't work with rails 4.2.5.2, ruby 2.3 and invoker 1.4.1

probably not invoker's issue per-say but does make it significantly less useful for development.

`img : [pry-remote] Waiting for client on druby://127.0.0.1:9876
img : [pry-remote] Client received, starting remote session
img : [pry-remote] Remote session terminated
img : [pry-remote] Ensure stop service
img :
img : Frame number: 0/167
img :
img : From:~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pry-remote-0.1.8/lib/pry-remote.rb @ line 321 Object#remote_pry:
img :
img :     319: def remote_pry(host = PryRemote::DefaultHost, port = PryRemote::DefaultPort, options = {})
img :     320:   PryRemote::Server.new(self, host, port, options).run
img :  => 321: end
img :
stty: stdin isn't a terminal
img : stty: stdin isn't a terminal
img : stty: stdin isn't a terminal
img : stty: stdin isn't a terminal
img : stty: stdin isn't a terminal
img : [1] pry(#<Binding>)> stty: stdin isn't a terminal`
